version: '3'
services:
  app:
    container_name: sejutacita-app
    image: sejutacita:latest
    restart: always
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    environment:
      - DB_HOST=mongo
      - DB_PORT=27017
      - DB_NAME=sejutacita
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodata
volumes:
  mongodata:
